package splitbyarc;

import java.awt.Toolkit;
import java.util.Random;
import tatukgis.jdk.TGIS_Color;
import tatukgis.jdk.TGIS_LayerVector;
import tatukgis.jdk.TGIS_Lock;
import tatukgis.jdk.TGIS_Point;
import tatukgis.jdk.TGIS_Shape;
import tatukgis.jdk.TGIS_ShapeArc;
import tatukgis.jdk.TGIS_ShapePolygon;
import tatukgis.jdk.TGIS_ShapeType;
import tatukgis.jdk.TGIS_Topology;
import tatukgis.jdk.TGIS_Utils;
import tatukgis.rtl.TObjectList;
import tatukgis.rtl.TPoint;

public class SplitByArcUI extends javax.swing.JFrame {

    public SplitByArcUI() {
        initComponents();
        initOwn();
    }
    
    private void initOwn(){
        btnSplit.setEnabled(false);
        
        GIS.Lock();
        
        GIS.Open(TGIS_Utils.GisSamplesDataDirDownload() + "/Samples/Topology/topology3.shp");
        
        layerPolygon = (TGIS_LayerVector)GIS.getItems().getItems(0);
        shpPolygon = (TGIS_ShapePolygon)layerPolygon.GetShape(1).MakeEditable();
        if(shpPolygon == null) return;
        
        layerArc = new TGIS_LayerVector();
        layerArc.getParams().getLine().setColor(TGIS_Color.getRed());
        layerArc.getParams().getLine().setWidth(25);
        if(layerArc == null) return;
        GIS.Add(layerArc);
        
        shpArc = (TGIS_ShapeArc)((TGIS_LayerVector)GIS.getItems().getItems(1)).CreateShape(TGIS_ShapeType.Arc);
        if(shpArc == null) return;
        shpArc.AddPart();
        
        layerObj = new TGIS_LayerVector();
        layerObj.setName("Splits");
        GIS.Add(layerObj);
        
        GIS.Unlock();
        
        GIS.FullExtent();
        GIS.setRestrictedExtent(GIS.getExtent());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLine = new javax.swing.JButton();
        btnSplit = new javax.swing.JButton();
        taShapeInfo = new javax.swing.JTextArea();
        GIS = new tatukgis.jdk.TGIS_ViewerWnd();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SplitByArc - TatukGIS DK11 sample");
        setFocusableWindowState(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/icon.png")));
        setSize(new java.awt.Dimension(800, 600));

        btnLine.setText("New line / Create line");
        btnLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLineActionPerformed(evt);
            }
        });

        btnSplit.setText("Split shape");
        btnSplit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSplitActionPerformed(evt);
            }
        });

        taShapeInfo.setEditable(false);
        taShapeInfo.setBackground(new java.awt.Color(240, 240, 240));
        taShapeInfo.setColumns(20);
        taShapeInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        taShapeInfo.setRows(5);

        GIS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GISMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                GISMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnLine))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnSplit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(taShapeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(GIS, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnLine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSplit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taShapeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
            .addComponent(GIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineActionPerformed
        layerObj.RevertShapes();
        shpArc.Reset();
        shpArc.AddPart();
        taShapeInfo.setText("...");
        GIS.InvalidateWholeMap();
        btnSplit.setEnabled(false);
    }//GEN-LAST:event_btnLineActionPerformed

    private void btnSplitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSplitActionPerformed
        int n;
        TGIS_Topology topologyObj;
        TObjectList<Object> shape_list;
        Random random;
        TGIS_Shape tmp;
        layerObj.RevertShapes();
        topologyObj = new TGIS_Topology();
        
        shape_list =  topologyObj.SplitByArc(shpPolygon, shpArc, true);
        if(shape_list != null){
            taShapeInfo.setText("Shapes after split: \n" + shape_list.getCount());
            random = new Random();
            for(n = 0; n < shape_list.getCount()  ; n++){
                ((TGIS_Shape)shape_list.getItems(n)).getParams().getArea().setColor(TGIS_Color.FromRGB(random.nextInt(255 ) * 256 * 256 + random.nextInt( 255 ) * 256 + random.nextInt( 256 )));
                tmp = (TGIS_Shape)shape_list.getItems(n);
                layerObj.AddShape((TGIS_Shape)shape_list.getItems(n));
            }
        GIS.InvalidateWholeMap();
        }
    }//GEN-LAST:event_btnSplitActionPerformed

    private void GISMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GISMousePressed
        TGIS_Point ptg;
        
        if(GIS.getIsEmpty()) return;
        ptg = GIS.ScreenToMap(new TPoint(evt.getX(), evt.getY()));
        shpArc.Lock(TGIS_Lock.Extent);
        shpArc.AddPoint(ptg);
        shpArc.Unlock();
        GIS.InvalidateWholeMap();
        if(shpArc.Intersect(shpPolygon)) 
            btnSplit.setEnabled(true);
    }//GEN-LAST:event_GISMousePressed

    private void GISMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GISMouseReleased
        TGIS_Point ptg;
        
        if(GIS.getIsEmpty()) return;
        
        ptg = GIS.ScreenToMap(new TPoint(evt.getX(), evt.getY()));
        shpArc.Lock(TGIS_Lock.Extent);
        shpArc.AddPoint(ptg);
        shpArc.Unlock();
        GIS.InvalidateWholeMap();
        if(shpArc.Intersect(shpPolygon)) btnSplit.setEnabled(true);
    }//GEN-LAST:event_GISMouseReleased


    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplitByArcUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplitByArcUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplitByArcUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplitByArcUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplitByArcUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tatukgis.jdk.TGIS_ViewerWnd GIS;
    private javax.swing.JButton btnLine;
    private javax.swing.JButton btnSplit;
    private javax.swing.JTextArea taShapeInfo;
    // End of variables declaration//GEN-END:variables
    private TGIS_LayerVector layerObj, layerPolygon, layerArc;
    private TGIS_ShapePolygon shpPolygon;
    private TGIS_ShapeArc shpArc;
}
