package reproject;

import java.awt.Toolkit;
import javax.swing.JFileChooser;
import tatukgis.jdk.TGIS_CSCoordinateSystem;
import tatukgis.jdk.TGIS_CSGeographicCoordinateSystem;
import tatukgis.jdk.TGIS_CSProjAbstract;
import tatukgis.jdk.TGIS_CSProjectedCoordinateSystem;
import tatukgis.jdk.TGIS_CSUnits;
import tatukgis.jdk.TGIS_LayerSHP;
import tatukgis.jdk.TGIS_LayerSqlGmMsSpatialJdbc;
import tatukgis.jdk.TGIS_LayerVector;
import tatukgis.jdk.TGIS_ShapeType;
import tatukgis.jdk.TGIS_Utils;

public class ReprojectUI extends javax.swing.JFrame {

    public ReprojectUI() {
        initComponents();
        initOwn();
    }
    private void initOwn(){
        int i;
        
        for(i = 0 ; i < TGIS_Utils.getCSProjList().Count() ; i++ ){
            projectionsComboBox.addItem(TGIS_Utils.getCSProjList().getProjection(i).getWKT());
        }
        GIS.Open(TGIS_Utils.GisSamplesDataDirDownload() + "/World/Countries/Poland/DCW/country.shp");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectionsComboBox = new javax.swing.JComboBox<>();
        btnReproject = new javax.swing.JButton();
        GIS = new tatukgis.jdk.TGIS_ViewerWnd();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reproject - TatukGIS DK11 sample");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/icon.png")));
        setMinimumSize(new java.awt.Dimension(800, 600));

        projectionsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectionsComboBoxActionPerformed(evt);
            }
        });

        btnReproject.setText("Reproject");
        btnReproject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReprojectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(projectionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReproject)
                .addGap(0, 465, Short.MAX_VALUE))
            .addComponent(GIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReproject))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GIS, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReprojectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReprojectActionPerformed
        TGIS_LayerVector lv, lo;
        int rVal;
        String filename, dir;
        
        if(GIS.getIsEmpty()) return;
        
        JFileChooser c = new JFileChooser();
        rVal = c.showSaveDialog(this);
        if(rVal == JFileChooser.APPROVE_OPTION){
            filename = c.getSelectedFile().getName();
            dir = c.getCurrentDirectory().toString();
        }else{
            filename = "";
            dir = "";
        }
        
        lv = (TGIS_LayerVector)GIS.getItems().getItems(0);
        lo = new TGIS_LayerSHP();
        lo.setPath(dir + "/" + filename);
        lo.setCS(GIS.getCS());
        lo.ImportLayer(lv, TGIS_Utils.GisWholeWorld(), TGIS_ShapeType.Unknown, "", false);
    }//GEN-LAST:event_btnReprojectActionPerformed

    private void projectionsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectionsComboBoxActionPerformed
        String proj = projectionsComboBox.getSelectedItem().toString();
        
        TGIS_CSGeographicCoordinateSystem ogcs = TGIS_Utils.getCSGeographicCoordinateSystemList().ByEPSG(4030);
        TGIS_CSUnits ounit = TGIS_Utils.getCSUnitsList().ByWKT("METER");
        TGIS_CSProjAbstract oproj = TGIS_Utils.getCSProjList().ByWKT(proj);
        
        TGIS_CSCoordinateSystem ocs = new TGIS_CSProjectedCoordinateSystem(
                     -1, "Test",
                     ogcs.getEPSG(), ounit.getEPSG(), oproj.getEPSG(),
                     TGIS_Utils.getCSProjectedCoordinateSystemList().DefaultParams(oproj.getEPSG())
                   );
         GIS.Lock();
            try
            {
                GIS.setCS(ocs);
                GIS.FullExtent();   
            }
            finally
            {
                GIS.Unlock();
            }    }//GEN-LAST:event_projectionsComboBoxActionPerformed

    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReprojectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReprojectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReprojectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReprojectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReprojectUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tatukgis.jdk.TGIS_ViewerWnd GIS;
    private javax.swing.JButton btnReproject;
    private javax.swing.JComboBox<String> projectionsComboBox;
    // End of variables declaration//GEN-END:variables
}
