package projections;

import java.awt.Toolkit;
import tatukgis.jdk.TGIS_CSCoordinateSystem;
import tatukgis.jdk.TGIS_CSGeographicCoordinateSystem;
import tatukgis.jdk.TGIS_CSProjAbstract;
import tatukgis.jdk.TGIS_CSProjectedCoordinateSystem;
import tatukgis.jdk.TGIS_CSUnits;
import tatukgis.jdk.TGIS_Utils;

public class ProjectionsUI extends javax.swing.JFrame {

    public ProjectionsUI() {        
        initComponents();
        initOwn();
    }

    @SuppressWarnings("unchecked")
    private void initOwn(){
        int i;
        for (i = 0; i < TGIS_Utils.getCSProjList().Count(); i++)
            {
                comboBox.addItem(TGIS_Utils.getCSProjList().getProjection(i).getWKT());
            }
        GIS.Open(TGIS_Utils.GisSamplesDataDirDownload() + "/Samples/Projects/world.ttkproject");
        GIS.InvalidateWholeMap();
        GIS.FullExtent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBox = new javax.swing.JComboBox();
        GIS = new tatukgis.jdk.TGIS_ViewerWnd();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projections - TatukGIS DK11 sample");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/icon.png")));
        setSize(new java.awt.Dimension(800, 600));

        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        GIS.setAutoCenter(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 560, Short.MAX_VALUE))
            .addComponent(GIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GIS, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        String proj = comboBox.getSelectedItem().toString();
        
        TGIS_CSGeographicCoordinateSystem ogcs = TGIS_Utils.getCSGeographicCoordinateSystemList().ByEPSG(4030);
        TGIS_CSUnits ounit = TGIS_Utils.getCSUnitsList().ByWKT("METER");
        TGIS_CSProjAbstract oproj = TGIS_Utils.getCSProjList().ByWKT(proj);
        
        TGIS_CSCoordinateSystem ocs = new TGIS_CSProjectedCoordinateSystem(
                     -1, "Test",
                     ogcs.getEPSG(), ounit.getEPSG(), oproj.getEPSG(),
                     TGIS_Utils.getCSProjectedCoordinateSystemList().DefaultParams(oproj.getEPSG())
                   );
         GIS.Lock();
            try
            {
                GIS.setCS(ocs);
                GIS.FullExtent();   
            }
            finally
            {
                GIS.Unlock();
            }
    }//GEN-LAST:event_comboBoxActionPerformed


    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectionsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectionsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectionsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectionsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectionsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tatukgis.jdk.TGIS_ViewerWnd GIS;
    private javax.swing.JComboBox comboBox;
    // End of variables declaration//GEN-END:variables
}
